### ISSUE TITLE
Dora not  compilling on Rust 1.29 nightly

### ISSUE THREAD

**Issue by aprokurov** [dinfuehr/dora#10]
I need help, can't compile dora on nightly toolchain
```
 rustc --version 
rustc 1.29.0-nightly (960f6046c 2018-07-08)

```

**Comment by dinfuehr** [comment]
Sorry for that. Can't fix it right now for some reasons. I will try to ping someone to fix it..

**Comment by aprokurov** [comment]
@dinfuehr i think i know how to fix it, i try to create pull request to fix that bug
