### ISSUE TITLE
macos test - stuck on starting your workflow

### ISSUE THREAD

**Issue by riginding** [dinfuehr/dora#104]
Multiple people seem to have this problem. I guess we will just have to wait till it gets fixed, we could stop the macOS test for now, if it annoys you :)

https://github.community/t5/GitHub-Actions/Stuck-on-quot-starting-your-workflow-run-quot/td-p/31702/page/2

**Comment by dinfuehr** [comment]
As long as this is fixed within a few days it is fine, if it takes longer we should disable it.

**Comment by dinfuehr** [comment]
Seems to be working again now
