### ISSUE TITLE
Implement additional bit twiddling intrinsics

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#117]
(This is probably a good beginner issue.)

There are a few operations that operate on integers that can be implemented manually, but could profit a lot from directly using the CPU's specially-built instruction for it.
All operations listed here have a direct counterpart in assembly.

The goal is to provide a method for these operations that make use of the special CPU instruction:

- [x] [POPCNT](https://www.felixcloutier.com/x86/popcnt) — Return the Count of Number of Bits Set to 1 (https://github.com/dinfuehr/dora/pull/131)
- [x] [LZCNT](https://www.felixcloutier.com/x86/lzcnt) — Count the Number of Leading Zero Bits (https://github.com/dinfuehr/dora/pull/131)
- [x] [TZCNT](https://www.felixcloutier.com/x86/tzcnt) — Count the Number of Trailing Zero Bits (https://github.com/dinfuehr/dora/pull/131)
- [x] [ROL, ROR](https://www.felixcloutier.com/x86/rcl:rcr:rol:ror) — Rotate Left/Rotate Right (https://github.com/dinfuehr/dora/pull/138)
- [x] [SHLX, SHRX, SARX](https://www.felixcloutier.com/x86/sarx:shlx:shrx) — Shift without doing stupid shit (https://github.com/dinfuehr/dora/pull/144)

For each of these instructions the following steps can be taken:

1. Add the method to `Int.dora`/`Long.dora` and mark it as `@internal`.
2. Add the method to the list of intrinsic functions in `prelude.rs`.
3. From there, you can use existing functions as an example of where and how to wire things up in `codegen.rs`.
4. Write tests to verify that the function works as expected. Make sure to identify and cover corner cases as well!

---

[Bit Manipulation Instruction Sets](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets) gives a good overview of additional operations that could be of interest.

**Comment by soc** [comment]
Further thoughts:

- Would it make sense to also add functions for the (trivial) inverse operations ("Count of Number of Bits Set to 0", "Number of Leading One Bits", "Number of Trailing One Bits")?
- What's a good, consistent naming scheme for these functions? Ideas:
  - `countZeroes/countOnes`, `countLeadingZeroes/countLeadingOnes`, `countTrailingZeroes/countTrailingOnes`
  - `countZeroBits/countOneBits`, `countLeadingZeroBits/countLeadingOneBits`, `countTrailingZeroBits/countTrailingOneBits`
  - `countZeroes/countOnes`, `countZeroesLeading/countOnesLeading`, `countZeroesTrailing/countOnesTrailing`
  - ...

**Comment by soc** [comment]
Hardware requirements:

- `POPCNT` requires at least Nehalem/K10
- `LZCNT requires at least Haswell/K10.
- `TZCNT` requires at least Haswell/Piledriver.

The newest instruction is therefore at least 7-8 years old – I'd think it would be reasonable to implement the bit ops without a fallback, and instead check on VM startup that the CPU is recent enough ...

**Comment by dinfuehr** [comment]
Personally I would simply assume that the CPU is recent enough and not implement a fallback or startup check at all ;)

But obviously feel free to implement whatever feels right to you.

**Comment by soc** [comment]
Makes sense! Maybe we should have code to deal with unsupported instructions in general though, because currently that crashes the runtime with

    error: trap not detected (signal 4, addr 0x7f114d840fe7).

Took me a while to figure out why the code was fine on my workstation, but fell apart on my old notebook. :-)

**Comment by soc** [comment]
Weird, the crash doesn't seem to be related to an unsupported instruction; I get the same on a machine that supports popcount.

**Comment by soc** [comment]
Let's close this and open individual issues for operations that may be worthwhile to implement.
