### ISSUE TITLE
"not-a-number".{parseInt,parseLong} returns 0

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#125]
We should probably return an `Option` instead.

**Comment by dinfuehr** [comment]
Absolutely. IIRC when I implemented those functions there was no Option class and no way to iterate strings from Dora. Might make sense to implement these functions in Dora as well instead of Rust now. Useful for this would might also be arithmetic instructions that detect overflow.

**Comment by soc** [comment]
Fixed in https://github.com/dinfuehr/dora/pull/129.
