### ISSUE TITLE
Identify all public non-total functions and consider replacements

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#126]
We should list all functions that throw exceptions on failure and think how we can make them not do that.

In some cases it might be as easy as change the return from `T|throws` to `Option[T]` or `Result[T]`.

In other cases it might be necessary to think of how to provide the functionality in a different way (e. g. encouraging the use of iterators or higher-order functions instead of indexing into an array).

The goal of this issue is to gather the insight first, such that considerations can cover the complete list of functions in question.

The overarching motivation is to reduce the number of control flow constructs a user has to keep in mind when reading code.

**Comment by soc** [comment]
Incomplete list (feel free to add more):

- [ ] Array#get
- [ ] Array#set

**Comment by dinfuehr** [comment]
Agreed, however I wouldn't change the return type for `Array#get` and `Array#set` to `Option[T]`. Additional methods that return an Option would be great though. At the moment those methods aren't declared throws either, it would just be too much boilerplate for array-heavy code without too much added value (most of the time folks would just write `array(idx).unwrap()` anyways. Following this logic even operations like `a / b` would have to return an option to handle div-by-0.

**Comment by soc** [comment]
> I wouldn't change the return type for Array#get and Array#set to Option[T]. 

Agreed to not changing it, at least not at this stage. Though my hope would be that we would have a rich enough iterator/collections/streaming API one day, that we would look back on this and say "the alternatives are so good and popular, changing get/set to not throw would have minimal impact".

Having the array operations as `Option` would actually be more regular with other collection's lookup operations like `Set#get` or `Map#get`, but I think there is still a long way to go before this can be considered.

> At the moment those methods aren't declared throws either, it would just be too much boilerplate for array-heavy code without too much added value [...]

Totally agree!

> Following this logic even operations like a / b would have to return an option to handle div-by-0.

Agreed, I have been thinking about this some time ago and how it can be dealt with without introducing lots of boilerplate.

**Comment by dinfuehr** [comment]
Agreed, let's revisit this later.

**Comment by soc** [comment]
I think the remaining ones are easily identified due to the mandatory `throws` keyword, or are there any other exceptions like for arrays that you can think of?

**Comment by dinfuehr** [comment]
None that I remember right now.

**Comment by soc** [comment]
Great, thanks!

**Comment by soc** [comment]
I documented the existing cases, I think this can be closed for now.

![panics](https://user-images.githubusercontent.com/42493/96386854-5dbb6800-119e-11eb-9d6d-15ef20481441.png)
