### ISSUE TITLE
Handle Int::minValue() / -1

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#142]
We deal with `x / 0`, but not with `Int::minValue() / -1`, which fails with

```
terminated by signal SIGFPE (Floating point exception)
```

on Intel.

**Comment by soc** [comment]
@dinfuehr very cool, thanks! Just for my understanding, why "negate lhs"?

**Comment by dinfuehr** [comment]
Instead of dividing by -1, we should be able to negate the value: x / (-1) ==> -x.

**Comment by soc** [comment]
But the only value this applies is minValue ... so is the negate a short way to get -1?

**Comment by dinfuehr** [comment]
Maybe I am missing something, the logic looks like this:

```
if rhs == -1 {
  -lhs
} else {
  lhs / rhs
}
```

Instead of dividing by -1 we negate `lhs`. We do that for every `lhs` - not just minValue.

**Comment by soc** [comment]
Ah, now I understand ... thanks! I was first thinking of `not`, not `neg`, and got confused.
