### ISSUE TITLE
Reproduce initialization issue in Throwable

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#156]
Mentioned in: https://github.com/dinfuehr/dora/pull/152#issuecomment-581076477

Problem appears when trying to replace

```
  var backtrace: Array[Int] = nil;
  var elements: Array[StackTraceElement] = nil;
```

with empty arrays as in https://github.com/dinfuehr/dora/pull/128/files#diff-fdd12e40f618e7564137f156b2f8ba69.

It seems that the variables are not initialized on instance creation.

**Comment by dinfuehr** [comment]
I guess this is not a bug, there is some [native code](https://github.com/dinfuehr/dora/blob/master/dora/src/exception.rs#L347-L356) as well that constructs an Exception but doesn't initialize those fields.

**Comment by soc** [comment]
Oh damn, didn't think about this – I'll have a look and try to add the init code to the native code too.

**Comment by dinfuehr** [comment]
Maybe that native code should simply invoke the Dora constructor?

**Comment by soc** [comment]
Do you mean via registering it in `prelude::known_methods` or differently?
