### ISSUE TITLE
Allow ==/!= for generic types if type implements Equals

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#214]
This should compile:

```
  fun equal[T : Equals](actual: T, expected: T) {
    if actual != expected {
      assert(false);
    }
  }
```

Instead, it fails with:

```
binary operator `!=` can not handle expression of type `T != T`
```

Instead, `equals` has to be used.

**Comment by dinfuehr** [comment]
Agreed. It's a known limitation, I did not implement this so far.

**Comment by soc** [comment]
I'm wondering with a bit of unease about the status of `===`/`!==` too.

While every type implements it (magically), I feel that generic types should require the `Identity` constraint for "honesty" reasons. What do you think?
