### ISSUE TITLE
panic with 'no machine mode for ().' on reference equality

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#22]
Consider this class:

    class Foo(i: int) {}

Works:

    let f1 = Foo(1);
    let f2 = Foo(2);
    assert(f1 !== f2);

Panics:

    assert(Foo(1) !== Foo(2));

**Comment by dinfuehr** [comment]
Hi, started to look into it but can't reproduce it:

```
fun main() {}
class Foo(i: int)
fun f() { assert(Foo(1) !== Foo(2)); }

fun g() {
  let f1 = Foo(1);
  let f2 = Foo(2);
  assert(f1 !== f2);
}
```
