### ISSUE TITLE
Precedence of &

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#240]
> So Ritchie maintained backwards compatibility forever and made the precedence order &&, &, ==, effectively adding a little bomb to C that goes off every time someone treats & as though it parses like +, in order to maintain backwards compatibility with a version of C that only a handful of people ever used.

[Eric Lippert: Hundred year mistakes](https://ericlippert.com/2020/02/27/hundred-year-mistakes/)

We should consider adjusting precedence based on this, some other languages that do it "correctly" are Swift, Go, Ruby and Python.

**Comment by dinfuehr** [comment]
Hmm, isn't this what we already do?

**Comment by dinfuehr** [comment]
Since I was already looking at the operator precedence, I shuffled it around a bit: https://github.com/dinfuehr/dora/commit/11c7a3b8a450c423fc7753072f30516abc8a739b

**Comment by soc** [comment]
I should write some tests for this ... :-)

**Comment by dinfuehr** [comment]
Sounds good.

**Comment by soc** [comment]
Ok, great!
