### ISSUE TITLE
0.0/0.0 produces different results on x86 and Arm/RiscV

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#256]
EDIT: Turns out this is not a bug in sorting, but caused by 0.0/0.0 producing different results on x86 and Arm/RiscV.

--- 

"negative" NaN and "positive" NaN are swapped:

```
// expected order
let nNaN = -(0.0/0.0);
let nInf = -1.0/0.0;
let nOne = -1.0;
let nZero = -0.0;
let pZero = 0.0;
let pOne = 1.0;
let pInf= 1.0/0.0;
let pNaN = 0.0/0.0;

// actual order
let x = Array[Float64](pOne, pInf, nInf, pNaN, nNaN, nZero, pZero, nOne);
Array[Float64]::sortStable(x);
assert(x(0L) === pNaN); // bug, should be at position 7
assert(x(1L) === nInf);
assert(x(2L) === nOne);
assert(x(3L) === nZero);
assert(x(4L) === pZero);
assert(x(5L) === pOne);
assert(x(6L) === pInf);
assert(x(7L) === nNaN); // bug, should be at position 0
```

spec:

> 5) If x and y are both NaNs, then totalOrder reflects a total ordering based on:
> i) negative sign orders below positive sign
> ii) signaling orders below quiet for +NaN, reverse for −NaN

**Comment by dinfuehr** [comment]
An additional complication: NaNs (IIRC) seem to have a slightly different encoding on arm64, so sortsAs behaves differently on arm64 than on x64 with the current implementation. I had to disable the test for [sorting](https://github.com/dinfuehr/dora/commit/c8d0e1858cdf42066496b5703b486ff89ec80396) because of this.

**Comment by soc** [comment]
Thanks, that's good to know!

**Comment by dinfuehr** [comment]
I guess sortsAs then needs to be able to handle NaNs with some payload as well, right?

**Comment by soc** [comment]
It should do that already, but it's possible that some architectures do not retain the exact payload.

(There is also the possibility that the quiet/signaling bit for NaNs is inverted. If you have the bitpattern it failed with then I can investigate further.)

**Comment by dinfuehr** [comment]
Apparently positive and negative NaN are swapped on arm64 vs x64:

```
# arm64
pNaN = 7FF8000000000000
nNaN = FFF8000000000000

# x64
pNaN = FFF8000000000000
nNaN = 7FF8000000000000
```

Maybe this is a bug in Dora on x64? It's a bit surprising to me that pNaN has the top-most bit set.

**Comment by soc** [comment]
I think this is related to Intel specifying a specific bit pattern "QNaN Floating-Point Indefinite" being returned by things like 0.0/0.0.

Rather than letting things be platform-specific, I think it would be better to specify the expected result and add the code to make platforms behave as desired.

**Comment by dinfuehr** [comment]
You mean ensuring this for e.g. fp division on x64? That would mean we need to pay some cost for this for each and every fp division even if that value is never used for sorting.

**Comment by soc** [comment]
I think having a reliable output makes sense, not only in sorting.

My plan was to check how the big platforms like Java and .NET do it.

**Comment by dinfuehr** [comment]
At least Java and JavaScript don't do this either. The reliable output is NaN, the exact bit pattern of NaN is platform-specific though.

**Comment by soc** [comment]
Java has a distinction between "raw" bits and not-"raw" bits when getting the bits of a double, the former fixes NaN values to `0x7ff8000000000000`/``0x7fc00000`.

**Comment by soc** [comment]
On Arm, DN of the FPCR (e. g. bit 25 on a A77) toggles between propagating NaN values and using a default NaN value `7ff8000000000000`/`7fc00000`.

**Comment by soc** [comment]
Ok, perhaps it makes sense to

- accept that the NaNs are different on different platforms
- document it in Sortable or `sortStable`
- add a way to run tests on select architectures only

What do you think @dinfuehr?

(And after that, we should probably check `Int64.minValue / -1` for architecture-specific differences.)

**Comment by dinfuehr** [comment]
Considering this I am not sure whether we should provide a total order for float/double at all.

There exists a test for this (maybe not for abs though): https://github.com/dinfuehr/dora/blob/master/tests/div-check.dora

**Comment by soc** [comment]
> Considering this I am not sure whether we should provide a total order for float/double at all.

Total order is crucial for being able to retrieve values from order-based collections, e. g. sorted sets and binary trees; the `Sortable` mechanism there is the equivalent to `Identity` for lookups in e. g. lists or hashmaps.

> There exists a test for this (maybe not for abs though)

I'm already working on additional tests, to make sure we have reliable bahvior across platforms in https://github.com/dinfuehr/dora/pull/258.

**Comment by dinfuehr** [comment]
The developer could always use a lambda for sorting (and e.g. assume/assert that no NaNs are used).

**Comment by soc** [comment]
I think this is hard to pull off, because without `Sortable` you lack the ability to define this generically for lambdas.

Even Java decided that was a bridge too far and made their `compare` methods implement (some) total order, instead of being consistent with their comparison operators.

**Comment by soc** [comment]
I updated the PR, adding `Int64::abs()` and tests for that.

**Comment by dinfuehr** [comment]
Not sure I understand, how is that hard to pull off? We coud have `sort()` for all types that implement `Sortable` and all other types need to use `sortWith(|a,b| { ... })` to implement their own sorting function (here the developer can choose how to handle NaNs).

**Comment by soc** [comment]
> Not sure I understand, how is that hard to pull off?

I think it's desirable in the future to be able to derive implementations for common traits, including `Equals`, `Comparable` and `Sortable`. If adding a float to a class or struct would stop derivation and required providing a manual implementation instead, this would be unnecessarily cumbersome.

> We could have sort() for all types that implement Sortable and all other types need to use sortWith(|a,b| { ... }) to implement their own sorting function (here the developer can choose how to handle NaNs).

I'm not seeing the benefit of that ... I believe in the wild this will turn into half a dozen subtly different comparison implementations for floats, that are all less reliable (because people don't think about edge cases until they get hit by it) and very likely slower than what the spec defines.

I don't see which problem this solves, but I see a lot of problems this will cause.

> there is the cost of the more complicated "total order" every time someone wants to sort floats, even when NaNs never occur

The sorting defined in the spec is pretty much as simple as it can get, pretty much shifts-only. It wouldn't get any faster or simpler by not handling NaNs, because there is zero code special-casing NaNs to start with.

Looking at Agner's instruction tables with a reasonably new architecture, the "normal" floating point comparison (fucom) has 11 units of latency alone, while total order has 1 (mov) + 1 (sarx) + 1 (shrx) + 1 (xor) = 4 at worst, and higher throughput.

Even if you doubled this number (suggesting that the instructions for the two values weren't independent), total ordering would still look better than float comparison.

Nothing beats actual measurement to verify this, but I'm very doubtful that any user-supplied ad-hoc implementation will beat either of comparison or total order; not in performance and not in correctness.

**Comment by soc** [comment]
From my POV the only thing that should be done is documenting that NaN payloads can differ between platforms, everything else works as desired and expected.

**Comment by dinfuehr** [comment]
Ah right, true. I thought we would do those bitwise instructions in addition to the fp-comparison. Although `(u)comiss` seems to have a latency of only 4 on Zen 1 (and 5 on Zen2/3). Did you also count the comparisons needed for picking the right return value at the end of sortsAs as well?

Still, that sorting of floats is platform-specific is extremely unfortunate. I guess HashMap (and HashSet) have the same problem, depending on how someone gets to NaN it might be able to acquire an already stored value - or not if the CPU used a slightly different NaN encoding. Not sure whether this can happen.

**Comment by soc** [comment]
> Although (u)comiss seems to have a latency of only 4 on Zen 1 (and 5 on Zen2/3).

Ah true, I ended up with the wrong comparison instruction!

> Did you also count the comparisons needed for picking the right return value at the end of sortsAs as well?

I left that out for both comparison and sorting, except that the former would get it out of the eflags and the latter out of gp registers, it's the same code.

> I guess HashMap (and HashSet) have the same problem, depending on how someone gets to NaN it might be able to acquire an already stored value - or not if the CPU used a slightly different NaN encoding. Not sure whether this can happen.

It's not a problem, as long as Dora doesn't support dumping its memory on one architecture and loading it on another, and even then I think one needs some very specific purpose-built code to trigger this.
