### ISSUE TITLE
Implement `cast`?

### ISSUE THREAD

**Issue by playXE** [dinfuehr/dora#27]
I think this is a very useful thing for pointer operations e.g: 
```rust
let array = cast<Array<Int>>(my_pointer)
```
Or to get value from pointer:
```rust
let ptr = cast<long>(pointer + offset);
let integer = cast<Int>(ptr);
```

**Comment by playXE** [comment]
Note about realization: we don't need to "change" value to new value when compiling code, we just need to change value size and type and make the compiler think that value has a new type and new size

**Comment by dinfuehr** [comment]
I don't think this works well with Dora's GC, there is `as` and `is` for type conversions and type checks which should be good enough.
