### ISSUE TITLE
`--emit-ast` doesn't do anything

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#288]
Looking at the code, it seems the functionality isn't there (anymore); is this intentional?

@dinfuehr Is there an alternative you would suggest for looking at the AST?

**Comment by dinfuehr** [comment]
The code for dumping the AST is in this [file](https://github.com/dinfuehr/dora/blob/master/dora-parser/src/ast/dump.rs). I probably forgot to invoke that when removing the cmdline parser.

**Comment by soc** [comment]
Alright, I'll have a look restoring it.

**Comment by dinfuehr** [comment]
Should be fixed for now in https://github.com/dinfuehr/dora/commit/9d1afed870658c1f37f26237cfa3184de66d9ab8
