### ISSUE TITLE
Adding a reference link for dora

### ISSUE THREAD

**Issue by abhi18av** [dinfuehr/dora#3]
Hii @dinfuehr,

From the code this seems like great project, I wanted to learn more about this `dora` language could you add a relevant link to your `README.md` please?

**Comment by dinfuehr** [comment]
Hi, unfortunately there is no documentation for the language right now. If you want to see how the dora language works, right now it is probably the best if you look into the [tests-directory](https://github.com/dinfuehr/dora/tree/master/tests).
