### ISSUE TITLE
How lazy compilation is protected in case of multiple threads?

### ISSUE THREAD

**Issue by playXE** [dinfuehr/dora#304]
Hello! I am making an JITed runtime for Scheme and I was looking at your code to see how lazy compilation is implemented (although I use very different backend [b3](https://github.com/playXE/b3-rs/)). I do not seem to find how synchronization is implemented. Runtime does not care if function was compiled multiple times?

**Comment by dinfuehr** [comment]
See [compilation.rs](https://github.com/dinfuehr/dora/blob/main/dora-runtime/src/vm/compilation.rs) which lets a second thread block until compilation of the same method/function is finished. And [lazy_compilation_stub.rs](https://github.com/dinfuehr/dora/blob/main/dora-runtime/src/compiler/lazy_compilation_stub.rs) is used to invoke the compiler for uncompiled methods and it also patches call-sites to directly invoke the compiled method when it gets re-executed later. Hope that helps!
