### ISSUE TITLE
Extend if-statements to if-expressions

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#39]
Allow

    let i = if false { 23; } else { 42; }

as a less imperative version of

    var i = 0;
    if false {
      i = 23;
    } else {
      i = 42;
    }

**Comment by dinfuehr** [comment]
This would be extremely cool!

It might make sense to make this similar to Rust, such that you can write `let i = if x { 1 } else { 2 }`, without the semicolon.

**Comment by soc** [comment]
Great to hear this is going into the right direction!

I also want to go a step further, and support switching/pattern matching later on (I always considered having both `if` and `switch`/`match` to be a language wart.

I have written about the general approach [here](https://soc.github.io/languages/unified-condition-syntax) altough I think Dora's syntactic structure (`{}` instead of `then` to introduce a then branch) require a slightly different approach:

Instead of

    if list
      .isEmpty       then "e"
      .contains(0.0) then "n"
                     else "z"

we could maybe do

    if list
    ..  .isEmpty       { "e" }
    ..  .contains(0.0) { "n" }
                     else "z"

**Comment by dinfuehr** [comment]
BTW I've started working on this.

**Comment by dinfuehr** [comment]
I guess this is good enough for now (see [if1.dora](https://github.com/dinfuehr/dora/blob/master/tests/if1.dora)). Still needs some refinement, Dora should also detect when `continue` and `break` leave regular control flow in one of the branches.

**Comment by soc** [comment]
@dinfuehr I wouldn't bother with `break` and `continue`; I'd rather get rid of those two altogether:

- The alternative of using an additional method feels only a slightly bit clunkier.¹
- In my experience the implementation complexity and the mental complexity for users has never been worth the convenience.

If you agree, I'd create an issue about dropping `break` and `continue` and work on that.

¹ I ported Java's `java.time` implementation from Java to Scala and had to deal with a lot of `break`s and `continue`s, and the replacements were never too bad – the biggest trouble was always understanding what the `break` or `continue` was trying to do in the first place.
