### ISSUE TITLE
Drop secondary constructors

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#43]
Having multiple constructors tends to be a source of huge complexity when it comes to deciding whether a field has been initialized, and combined with chained constructor calls or parent constructor calls they enable writing hard to understand code.

I propose dropping secondary constructors, allowing only zero (for things like `Nothing`) or one primary constructor. This also discards function overloading as a language concept.

Instead, it encourages the use of static factory methods (which all call the single constructor), which have the huge benefit of allowing individual, descriptive names (while constructors are unnamed).

They are also more flexible in what they can return, as they can not only return `T`, but also things like `Option<T>` or `Result <T>`, while constructors can only return `T`, making error handling quite awkward.

**Comment by dinfuehr** [comment]
I agree, getting rid of function overloading makes a lot of sense. IIRC it wasn't so simple to implement and as a user there might be some surprising edge cases...
