### ISSUE TITLE
Introduce Hash trait, immutable flag on Class and runtime magic to cache hashcodes

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#47]
1. Add a `Hash` trait:
```
trait Hash {
  fun hash() -> Int;
}
```

2. Add `is_immutable` to `Class` and let the compiler set it based on the following rules:
  - An `open` class is mutable.
  - A `var` field makes the class is mutable.
  - A `let` field with a primitive type is immutable.
  - A `let` field with a reference type which is itself immutable is immutable.

3. Use one of the unused lower bits of the vtable pointer of an instance (we align by 8 bytes, so we have 3 bits to spare) as a "hash is cached bit".

4. Move the layout of an immutable class C for which `sizeOf<C> % 8 >= 4` by 4 bytes, freeing up 4 bytes after between the instance header and the first field in the new layout.

5. Emit additional code for `fun hash`: Check whether the "hash is cached bit" is set and ...
  - if true, return the value of the 4 bytes in the beginning.
  - if false, compute the hashcode, stores the result in the first 4 bytes and set the "hash is cached bit"

**Comment by soc** [comment]
@dinfuehr What do you think? While I think there is a concern regarding predictability, I think it would be a cool way for the runtime to opportunistically cache hashcodes, speeding up every data-structure that uses it, because things are never computed more than once (modulo harmless race conditions).

**Comment by dinfuehr** [comment]
I am not a fan of adding such magic in general: A class can always cache the hash itself and have some behavior that fits for its use case (e.g. recomputing the hash when setting a field).

I am also not sure whether it makes sense to steal bits from the vtable pointer. This requires us to mask out the low 3-bits when loading something from the vtable ptr, this introduces some overhead. Although not sure how much. However we could steal a bit from the header word - the word right after the vtable pointer in an object (used by the GC for the forwarding pointer and marking bit).

**Comment by soc** [comment]
I agree with you regarding magic in general.

In this case my experience is that people rarely cache hashcodes, because often they are fine with caching it when it's free (in terms of instance size), but don't want to pay the overhead. Usually the concern is that the next person might add another field without considering the instance size, turning their "free" hashcode into one with cost attached.

So I'm not sure it is worth it, but I thought that the hashcode magic in the runtime alleviated some of these concerns.

In addition to that, there are some hashmap implementations which cache the hashcodes externally. With this feature, this could be elided for classes which already cache it internally. The benefit compared to manually caching the hashcode is that in this case the position of the cached hashcode is guaranteed, so instead of calling the `hash` method, it could read the field directly.

**Comment by dinfuehr** [comment]
> In addition to that, there are some hashmap implementations which cache the hashcodes externally. With this feature, this could be elided for classes which already cache it internally. The benefit compared to manually caching the hashcode is that in this case the position of the cached hashcode is guaranteed, so instead of calling the `hash` method, it could read the field directly.

Not sure this makes much of a difference: A HashMap has to be specialized for each key/value combination anyway, inlining hash() should then give the same result.

I am not opposed to this, but this seems to require a lot of language features to work properly. Let's postpone this discussion to a later date for now.

**Comment by soc** [comment]
Agreed. Shall I close this issue or do we want to create a few of these issue tags Github offers and start tagging issues with it (e. g. this one with "postponed" or something)?

**Comment by dinfuehr** [comment]
I am fine with whatever you prefer!

**Comment by soc** [comment]
I just checked https://github.com/dinfuehr/dora/labels and there seem to exist some tags, but nothing like "postponed".  Could you create such a tag and tag this issue with it (I can do neither of those things) _and_ close it?

(I would keep open tickets only for those issues we agree that they should/could be done and can be completed in a reasonable time frame, and distinguish between closed ones we have rejected and ones we might reconsider with tags like "postponed", "rejected", etc.)
