### ISSUE TITLE
Module design

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#53]
As promised, here is my design proposal for modules:

Modules are intended to act as

1. package declarations, like `package foo.bar;` or similar in traditional languages
2. the "holders" of static functions in classes (with the effect of being able to drop the `@static` annotation)
3. the "holders" of free-standing functions

There is only one keyword `module`, which introduces modules of two flavors, namely as
- an "open" module
- a "closed" module

### Outline

```
// file Cell.dora
module foo::bar; // 1. open module

class Cell[T](let value: T) { .... }

module Cell { // closed module
  // 2. this function would have lived as `@static fun ofOne() ...` in `class Cell`
  fun ofOne() -> Cell[Int] = Cell[Int](1);
}

// 3. a free-standing function, now namespaced in `foo::bar`
fun defaultCell() -> Cell[Int] = Cell::ofOne();
```

Our `module foo::bar` declaration (1.) at the top declares an _open_ module. 

The module declaration takes effect on everything defined in the file.
Instead of `Cell` living in a global namespace, it now lives under `foo::bar::Cell`.

_Open_ means that users can add to this module simply by creating a new file, adding the same module declaration at the top and defining additional classes, modules and functions:

```
// file Person.dora
module foo::bar;
class Person(let name: String, let age: Int) { ... }
```

Unlike our module declaration, modules declared inside a file are _closed_ modules.

This means that in our case (2.), the only way to add another element to our `module Cell` is to edit the file "Cell.dora" and add another member:

```
// modified file Cell.dora
module foo::bar;
...
module Cell {
  fun ofOne() -> Cell[Int] = Cell[Int](1);
  fun ofTwo() -> Cell[Int] = Cell[Int](2); // added another function
}
...
```

Free-standing functions (3.) look the same, but the module declaration has the same effect on them as they have on classes and modules in the file:

Given the module declaration `foo::bar`, the full path of `defaultCell` becomes `foo::bar::defaultCell()` – the module `foo::bar` is the "holder" of the free-standing function.

### Reasoning

The two points important for me are a) the unification of "packages" &"modules", giving them the same rules and semantics, and b) establishing a clear separation between elements that exist "per-class" and elements that exist "per-instance" of a class.

With (closed) modules rules become very simple:

- Everything within a `class` exists once for each instance of that class.
- Everything within a `module` exists once.

This also eliminates much of the confusion a user might have regarding generics between static and non-static functions (type parameters are only in scope for non-static functions; a type parameters declared on a function with the same name as a type parameter on a class _shadows_ the class' type parameter if it is a non-static function, while for a static function the type parameter of the class is simply not in scope, etc. etc.) and reduces many of the hurdles beginners face like "why can't my static function not access other functions/values despite all of them being in the same class?" (answer: they are not static).

### Open Questions

- how to represent in the AST?
- how to deal with `@static` methods in traits?
- free-standing functions are not strictly necessary, should we dropp or constrain them?

### References

todo: lessons learned from other programming languages with similar features

**Comment by dinfuehr** [comment]
LGTM, I have some questions to clarify:

* So a file say `x/y/z1.dora` could be in package `foo::bar`, while `x/y/z2.dora` might be in package `some::other`? Modules are completely distinct from the file structure? Not saying this has to be the case, but we could think about something like this. E.g. `module some;` includes all *.dora-files in the directory `some`.
* How would you invoke Dora with multiple source files. Right now Dora can be started with either exactly one input file or directory. When we need multiple input files we probably need changes to the command line parser and use `--` to separate input files from the arguments to the Dora program.

**Comment by dinfuehr** [comment]
Forgot this: I guess we should then also discuss how we want to include libraries into Dora

**Comment by soc** [comment]
> So a file say x/y/z1.dora could be in package foo::bar, while x/y/z2.dora might be in package some::other? Modules are completely distinct from the file structure? Not saying this has to be the case, but we could think about something like this. E.g. module some; includes all *.dora-files in the directory some.

I think what's important for me is that one can use a single folder with various files with potentially different module declarations. It might make sense to support both, a flat hierarchy for small things like scripts and a full blown hierarchy where the folder structure follows the module declarations (and the compiler would warn if a file was incorrectly placed somewhere else).

But that's coming from the perspective of someone who finds Rust's approach rather unintuitive and confusing. :-)

> How would you invoke Dora with multiple source files. Right now Dora can be started with either exactly one input file or directory. When we need multiple input files we probably need changes to the command line parser and use -- to separate input files from the arguments to the Dora program.

> I guess we should then also discuss how we want to include libraries into Dora

I imagine that every library would consist of either flat files or a directory hierarchy combined with a metadata file that defines the name, author, version, dependencies and so on. Now put those things into a tar or zip file.

I propose calling such an archive a crate (for the lack of a better name).

Depending on code in Dora would work on the level of those crates. You could distribute those archives and refer to them by the crate name.

So you could say `dora --crate my.module` and Dora would resolve the dependencies specified in your metadata file of your crate `my.module` and run your crate.

One important thing here is that dependencies should not be transitive: If crate B depended on crate A, and crate C would depend on crate B, it wouldn't get crate A for free, it would need to explicitly depend on it.

**Comment by soc** [comment]
This is resolved/outdated.
