### ISSUE TITLE
Registering an external symbols

### ISSUE THREAD

**Issue by playXE** [dinfuehr/dora#54]
This feature allows interfacing with other languages much easier. I know there is `loadFunction` function for loading extern symbols but it's not easy to use since you need to convert your objects to `long` type. The easiest way to load external symbols is to use `dlsym`, that's what cranelift does.
```rust
#[cfg(not(windows))]
fn lookup_with_dlsym(name: &str) -> *const u8 {
    let c_str = CString::new(name).unwrap();
    let c_str_ptr = c_str.as_ptr();
    let sym = unsafe { libc::dlsym(libc::RTLD_DEFAULT, c_str_ptr) };
    if sym.is_null() {
        panic!("can't resolve symbol {}", name);
    }
    sym as *const u8
}
```
And this is how syntax may look for external functions:
`extern fun printf(String,...) -> Int;`
And this is how static values can be loaded
```
extern static SOMETHING: long; 
```
Also as I understand Dora calling convention for class methods similar to C++ calling convention and maybe this can be used to interface C++ classes,example:
```java
extern class SomeClass
{
     extern fun something() -> int;
}
```

**Comment by dinfuehr** [comment]
Let's close this until Dora is more mature.
