### ISSUE TITLE
"Direct" implementation of traits

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#56]
I think it would make sense to allow classes (and structs) to directly implement traits, such that

```
class Foo(...) {
  fun compareTo(rhs: Foo) -> Int = ...
}

impl Comparable for Foo {
  fun compareTo(other: Foo) -> Int = self.compareTo(other);
}
```

can be written as

```
class Foo(...) <keyword> Comparable {
  fun compareTo(rhs: Foo) -> Int = ...
}
```

In addition to that, I think it would make sense that `impl`s – whose fun-to-be-implemented exists with the exact signature in the `class` – do not require writing down the function if the classes' implementation matches:

```
class Foo(...) {
  fun compareTo(rhs: Foo) -> Int = ...
}

impl Comparable for Foo {} // no definition of compareTo necessary.
```

**Comment by soc** [comment]
I think the hardest part is deciding how the class syntax should look like. I propose using either `with` or `supports` as the keyword, but I don't have a too strong opinion on that.

One problem is that if the class already has an inheritance relationship, the syntax would look kinda weird:

```
class Foo(...) : Bar(...) supports Comparable {
  fun compareTo(rhs: Foo) -> Int = ...
}
```

It feels like this creates a much stronger visual connection between `Bar` and `Comparable` than between `Foo` and `Comparable`, which I believe is undesirable.

On the other hand, I kind of dislike the use of `:` for different things, so maybe this is a good way to tackle this issue:

```
class Foo(...) extends Bar(...) supports Comparable {
  fun compareTo(rhs: Foo) -> Int = ...
}
```

Based on the exact keyword chosen for direct trait implementations, the naming scheme of traits would need to be adapted:

```
... supports Comparable
... supports Sortable
... supports Equals
... supports Identity

... with Comparable
... with Sortable
... with Equals
... with Identity
```

In both cases there are combinations that sound off.

Maybe there is a consistent selection of names, but I have a hard time figuring it out:
```
supports: Comparing, Sorting, Equality, Identity
with: Comparable, Sortable, Equatable, Identifiable
```

**Comment by soc** [comment]
I have worked on this and added the required logic to the parser and ast parts.

I think the next step would be to add the direct implementations of traits to the VM's list of `impl`s.

@dinfuehr Do you have a suggestion at which point this should happen?

**Comment by dinfuehr** [comment]
AFAIU this feature should just be syntactic sugar, so ideally it should be implemented exclusively in the front-end and generate the same data in `vm.impls`, but not sure whether `ImplData` is ready for this now. So this might have to be changed first.

When you want to work on `impl`, IMHO it would be better to work on allowing to implement traits for generic classes (so implementing Default for Option[T] doesn't work).

**Comment by soc** [comment]
> so implementing Default for Option[T] doesn't work

Do you mean "does work", or am I misunderstanding something?

**Comment by dinfuehr** [comment]
Oh sorry, I meant that implementing Default for Option[T] doesn't work *at the moment*.

**Comment by soc** [comment]
Ahh, ok, thanks, understood!
