### ISSUE TITLE
Panic: 'fp-register accessed as gp-register'

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#59]
```
fun main() {

  // works
  0.0 == 0.0;
  // BUG: thread 'main' panicked at 'fp-register accessed as gp-register.', 
  0.0.equals(0.0);
  // works
  0.0 === 0.0;
  // BUG: thread 'main' panicked at 'fp-register accessed as gp-register.', 
  0.0.identicalTo(0.0);
}
```

**Comment by soc** [comment]
Any idea what to do here? I think the error may be caused by a missing check whether the argument works on fp regs instead of gp regs for the type instantiated in the generic code and used in e. g. `identicalTo`.

**Comment by dinfuehr** [comment]
I think that some code assumes that self can be stored in a general purpose register. I will try to take a look this weekend...
