### ISSUE TITLE
Rewrite x(y) to x.get(y) and x(y) = z to x.set(y, z)

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#72]
After the [generic syntax overhaul](https://github.com/dinfuehr/dora/pull/55) is done, I want to implement the syntactic rule that `x(y)` desugars to `x.get(y)` and `x(y) = z` to `x.set(y, z)` if `x` is not a function.

This allows us to not only recover "nice" syntax for arrays ...

```
  let e = foo.x.get(2);        // replace with let e = foo.x(2);
  foo.x.set(3, 456);          // replace with foo.x(3) = 456;
```

... but also allows us to use this syntax for lists, maps, strings, etc.

```
let firstElem = someList(0);
let secondByte = someString(1);
let capital = countriesAndCapitalsMap("Austria"); // "Vienna"
```

From a typechecking perspective the idea is to probably introduce a `Getter` and `Setter` trait that communicate these possibilities. An alternative would be to do a structural check, which might be more flexible.

**Comment by soc** [comment]
WIP is https://github.com/soc/dora/pull/2.

**Comment by soc** [comment]
@dinfuehr Shall we close this?

**Comment by dinfuehr** [comment]
I think this is done.

**Comment by soc** [comment]
Great!
