### ISSUE TITLE
Drop break and continue control-flow keywords

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#99]
Extracted from https://github.com/dinfuehr/dora/issues/39:

I'd like to get rid of those two control-flow keywords. Reasoning:

- The alternative of using an additional method feels only a slightly bit clunkier to write and vastly easier to read and understand when coming back after a month.¹
- In my experience the implementation complexity and the mental complexity for users has never been worth the "convenience".
- There aren't much reasons for `break` and `continue` to exist in general – it feels like this is something that got copied from C and keeps getting copied without anyone questioning it much. I certainly think that if `break` and `continue` didn't exist today, we wouldn't invent it.

Prior art:

One language that did away with `continue` is Scala; and in the last 10 years I never heard a single complaint about it. (`break` in Scala is done as a library (that throws exceptions) – I rather not go this way either.)

---

¹ I ported Java's `java.time` implementation from Java to Scala and had to deal with a lot of `break`s and `continue`s, and the replacements were never too bad. Replacing `break`s is almost trivial – `continue` is a bit more involved, but barely ever used.

The biggest trouble was always understanding what the `break` or `continue` was trying to do in the first place – a problem we won't have without `break` and `continue` in the first place.

**Comment by soc** [comment]
One additional reason is that it prevents building pure library-defined resource handling:

Consider

```
fun use[R : Closeable, T](resource: R, function: T -> Unit) {
    function();
    resource.close();
}
while ... {
  use(someFile, |x| { printFile(someFile); if someFile.isEmpty() { break; } } );
}
```

"Use `do ... finally ...` in the `use` function" would be the obvious answer, but in the long term I'd like to adopt a Rust-like approach where exceptions are only used for fatal errors that require aborting the program.

Not having `break`, `continue` and exceptions for control flow would allow us to replace `finally` by a pure library implementation.

**Comment by dinfuehr** [comment]
Haven't looked at the PR so far.

Don't get your argument here though and would be curious what I am missing here: break/continue/return only work inside the current function or closure. So the example above would fail to compile (is there missing something?). How would you implement resource handling "as a library" in Dora?

**Comment by soc** [comment]
Feel free to substitute `break` with `throw`; but I agree with you that it is the least compelling point listed here. Feel free to disregard it.

**Comment by dinfuehr** [comment]
I don't get why `break`/`continue` are different in this regard. It seems that even `return` would break resource handling already. How would you otherwise ensure that the `close`-function is run (without finally or defer)?

**Comment by soc** [comment]
If the intended language semantics are that `break`/`continue`/`return` only work inside the current closure, then they can't cause this issue; then only `throw` remains. As mentioned, I withdraw the point, because it detracts from the three better ones.
